"""Turn a golden vector set into board load files.

Usage:
    python -m stalyanpu.board.ddrimage <golden_dir> <out_dir> [--name NAME]

The golden directory is what ``stalyanpu golden`` or ``golden.demo`` writes:
``mem.hex`` (blob plus input image, sparse 128-bit words at absolute DDR
addresses) and ``golden.json`` (descriptor list base and count, output
regions with CRC32). The output directory receives:

- ``chunk_<addr>.bin``: one binary file per contiguous DDR range
- ``load.gdb``: gdb commands that restore the chunks into DDR
- ``testset.h``: C header with the descriptor list and the region table
"""

from __future__ import annotations

import argparse
import json
import os

from ..golden.hexfmt import read_hex


def write_set(golden_dir: str, out_dir: str, name: str) -> None:
    meta = json.load(open(os.path.join(golden_dir, "golden.json")))
    ranges = read_hex(os.path.join(golden_dir, "mem.hex"))
    os.makedirs(out_dir, exist_ok=True)

    gdb = ["# generated by stalyanpu.board.ddrimage from %s" % golden_dir]
    total = 0
    for addr, data in ranges:
        fn = "chunk_%08x.bin" % addr
        with open(os.path.join(out_dir, fn), "wb") as fh:
            fh.write(data)
        gdb.append("restore %s binary 0x%08x" % (fn, addr))
        total += len(data)
    with open(os.path.join(out_dir, "load.gdb"), "w", newline="\n") as fh:
        fh.write("\n".join(gdb) + "\n")

    regions = meta["regions"]
    lines = [
        "/* generated by stalyanpu.board.ddrimage from %s */" % golden_dir,
        "#ifndef TESTSET_H",
        "#define TESTSET_H",
        "",
        '#define TESTSET_NAME       "%s"' % name,
        "#define TESTSET_BLOB_BASE  0x%08Xu" % meta["base"],
        "#define TESTSET_DESC_BASE  0x%08Xu" % meta["desc_base"],
        "#define TESTSET_DESC_COUNT %du" % meta["desc_count"],
        "#define TESTSET_N_REGIONS  %d" % len(regions),
        "",
        "struct testset_region {",
        "    const char *name;",
        "    unsigned int base;",
        "    unsigned int bytes;",
        "    unsigned int crc32;",
        "};",
        "",
        "static const struct testset_region testset_regions[TESTSET_N_REGIONS] = {",
    ]
    for r in regions:
        lines.append('    { "%s", 0x%08Xu, %uu, 0x%08Xu },' % (r["name"], r["base"], r["bytes"], r["crc32"]))
    lines += ["};", "", "#endif /* TESTSET_H */", ""]
    with open(os.path.join(out_dir, "testset.h"), "w", newline="\n") as fh:
        fh.write("\n".join(lines))

    print("%s: %d chunks, %.1f MB of DDR data, %d descriptors, %d regions"
          % (name, len(ranges), total / 1e6, meta["desc_count"], len(regions)))


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("golden_dir")
    p.add_argument("out_dir")
    p.add_argument("--name", default=None, help="set name printed by the test (default: golden dir name)")
    a = p.parse_args(argv)
    write_set(a.golden_dir, a.out_dir, a.name or os.path.basename(os.path.normpath(a.golden_dir)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
