"""Render the ISA description to a C header for the bare metal driver."""

from __future__ import annotations

import os

from . import isa

DEFAULT_OUT = os.path.normpath(os.path.join(
    os.path.dirname(__file__), "..", "..", "..", "sw", "include", "stalyanpu_isa.h"))


def render_header() -> str:
    L = []
    L.append("/* Generated by stalyanpu.backend.gen_header from isa.py. Do not edit. */")
    L.append("#ifndef STALYANPU_ISA_H")
    L.append("#define STALYANPU_ISA_H")
    L.append("")
    L.append("#include <stdint.h>")
    L.append("")
    L.append(f"#define SNPU_ISA_VERSION   {isa.ISA_VERSION}")
    L.append(f"#define SNPU_DESC_WORDS    {isa.DESC_WORDS}")
    L.append(f"#define SNPU_DESC_BYTES    {isa.DESC_BYTES}")
    L.append(f"#define SNPU_BLOB_MAGIC    0x{isa.BLOB_MAGIC:08X}u")
    L.append("")
    L.append("/* Opcodes (descriptor word 0, bits 7:0). */")
    for name, val in isa.OPCODES.items():
        L.append(f"#define SNPU_OP_{name:<12s} 0x{val:02X}")
    L.append("")
    L.append("/* Flags (descriptor word 0, bits 23:8). Values are bit positions inside the field. */")
    for name, bit in isa.FLAGS.items():
        L.append(f"#define SNPU_FLAG_{name:<12s} (1u << {bit})")
    L.append("")
    L.append("/* Error codes reported in STATUS[15:8]. */")
    for name, val in isa.ERRORS.items():
        L.append(f"#define SNPU_ERR_{name:<12s} {val}")
    L.append("")
    L.append("/* CSR byte offsets inside the APB window. */")
    for off, name, access, doc in isa.CSR:
        L.append(f"#define SNPU_REG_{name:<12s} 0x{off:02X}  /* {access}: {doc} */")
    L.append("")
    L.append("/* Descriptor field accessors: word index, lsb and mask. */")
    for f in isa.FIELDS:
        n = f.name.upper()
        L.append(f"#define SNPU_DF_{n}_WORD {f.word}")
        L.append(f"#define SNPU_DF_{n}_LSB  {f.lsb}")
        L.append(f"#define SNPU_DF_{n}_MASK 0x{f.mask:X}u")
    L.append("")
    L.append("static inline uint32_t snpu_desc_get(const uint32_t *d, int word, int lsb, uint32_t mask)")
    L.append("{")
    L.append("    return (d[word] >> lsb) & mask;")
    L.append("}")
    L.append("")
    L.append("static inline void snpu_desc_set(uint32_t *d, int word, int lsb, uint32_t mask, uint32_t v)")
    L.append("{")
    L.append("    d[word] = (d[word] & ~(mask << lsb)) | ((v & mask) << lsb);")
    L.append("}")
    L.append("")
    L.append("struct snpu_desc {")
    L.append(f"    uint32_t w[{isa.DESC_WORDS}];")
    L.append("};")
    L.append("")
    L.append("struct snpu_blob_hdr {")
    for name, doc in isa.BLOB_HEADER:
        L.append(f"    uint32_t {name:<14s} /* {doc} */")
    L.append("};")
    L.append("")
    L.append("struct snpu_output_entry {")
    for name, doc in isa.OUTPUT_ENTRY:
        L.append(f"    uint32_t {name:<14s} /* {doc} */")
    L.append("};")
    L.append("")
    L.append("_Static_assert(sizeof(struct snpu_desc) == SNPU_DESC_BYTES, \"descriptor size\");")
    L.append("")
    L.append("#endif /* STALYANPU_ISA_H */")
    return "\n".join(L) + "\n"


def write_header(path: str = DEFAULT_OUT) -> str:
    text = render_header()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="\n") as fh:
        fh.write(text)
    return path


def check_header(path: str = DEFAULT_OUT) -> bool:
    """True when the file on disk matches the current ISA description."""
    if not os.path.exists(path):
        return False
    with open(path, newline="") as fh:
        return fh.read() == render_header()
