#!/usr/bin/env python3
"""Generate port-only stub modules for the IP instantiated by ti375_oob_top.v.

Many of the IPs are encrypted, so the top level cannot be compiled as is. A
stub keeps a module's header and port declarations and drops its body. That
is enough for Icarus Verilog to elaborate the top level and check its wiring:
an unknown port name is an error, a width mismatch a warning, and with
-Wimplicit a misspelt net shows up as an implicit declaration.

    make_stubs.py <project dir> <output file> <module>=<source file> ...
"""
import re
import sys

DECL = re.compile(r'^\s*(input|output|inout|parameter|localparam)\b')


def strip_comments(text):
    text = re.sub(r'/\*.*?\*/', lambda m: '\n' * m.group(0).count('\n'), text, flags=re.S)
    return re.sub(r'//[^\n]*', '', text)


def header_end(text, start):
    """Index just past the ';' that ends a module header, skipping #( ) and ( )."""
    depth = 0
    for i in range(start, len(text)):
        c = text[i]
        if c == '(':
            depth += 1
        elif c == ')':
            depth -= 1
        elif c == ';' and depth == 0:
            return i + 1
    raise ValueError("unterminated module header")


def stub(path, name):
    text = strip_comments(open(path, errors='replace').read())
    m = re.search(r'\bmodule\s+' + re.escape(name) + r'\b', text)
    if not m:
        raise SystemExit(f"{name}: module not found in {path}")
    end = header_end(text, m.end())
    out = [text[m.start():end]]

    # Non-ANSI headers declare their ports after the header. Keep statements
    # while they are declarations; stop at the first real body statement or
    # at an encryption envelope.
    rest = text[end:]
    for stmt in rest.split(';'):
        s = stmt.strip()
        if not s:
            continue
        if s.startswith('`pragma') or 'pragma protect' in s or s.startswith('endmodule'):
            break
        if s.startswith('`'):                   # `include / `define lines
            continue
        if DECL.match(s):
            out.append(s + ';')
            continue
        break
    out.append('endmodule')
    return '\n'.join(out) + '\n'


def main():
    if len(sys.argv) < 4:
        raise SystemExit(__doc__)
    out_path = sys.argv[2]
    parts = ['// Generated by make_stubs.py: port-only stubs, do not edit.\n`timescale 1ns / 1ps\n']
    for spec in sys.argv[3:]:
        name, path = spec.split('=', 1)
        parts.append(stub(path, name))
    open(out_path, 'w').write('\n'.join(parts))


if __name__ == '__main__':
    main()
