/* Generated by stalyanpu.backend.gen_header from isa.py. Do not edit. */
#ifndef STALYANPU_ISA_H
#define STALYANPU_ISA_H

#include <stdint.h>

#define SNPU_ISA_VERSION   1
#define SNPU_DESC_WORDS    32
#define SNPU_DESC_BYTES    128
#define SNPU_BLOB_MAGIC    0x534E5055u

/* Opcodes (descriptor word 0, bits 7:0). */
#define SNPU_OP_NOP          0x00
#define SNPU_OP_CONV         0x01
#define SNPU_OP_MAXPOOL5     0x02
#define SNPU_OP_COPY         0x03
#define SNPU_OP_BARRIER      0x04
#define SNPU_OP_END          0xFF

/* Flags (descriptor word 0, bits 23:8). Values are bit positions inside the field. */
#define SNPU_FLAG_SILU         (1u << 0)
#define SNPU_FLAG_RESIDUAL     (1u << 1)
#define SNPU_FLAG_IRQ          (1u << 2)
#define SNPU_FLAG_LAST         (1u << 3)
#define SNPU_FLAG_UPS0         (1u << 4)
#define SNPU_FLAG_UPS1         (1u << 5)
#define SNPU_FLAG_TWO_SRC      (1u << 6)
#define SNPU_FLAG_L0_MODE      (1u << 7)
#define SNPU_FLAG_WAIT_PREV    (1u << 8)
#define SNPU_FLAG_DEBUG_DUMP   (1u << 9)

/* Error codes reported in STATUS[15:8]. */
#define SNPU_ERR_NONE         0
#define SNPU_ERR_BAD_OPCODE   1
#define SNPU_ERR_BAD_CRC      2
#define SNPU_ERR_BAD_VERSION  3
#define SNPU_ERR_AXI_READ     4
#define SNPU_ERR_AXI_WRITE    5
#define SNPU_ERR_TIMEOUT      6
#define SNPU_ERR_GEOMETRY     7

/* CSR byte offsets inside the APB window. */
#define SNPU_REG_ID           0x00  /* RO: 0x534E5055 ('SNPU') */
#define SNPU_REG_VERSION      0x04  /* RO: hardware version, major << 8 | minor */
#define SNPU_REG_GEOMETRY     0x08  /* RO: n_chain[7:0] | chain_len[15:8] | log2(p_max)[19:16] | ibuf_kb[31:20] */
#define SNPU_REG_CTRL         0x0C  /* RW: bit0 start (self clearing), bit1 abort, bit2 soft reset */
#define SNPU_REG_STATUS       0x10  /* RO: bit0 busy, bits[15:8] error code, bits[31:16] current descriptor index */
#define SNPU_REG_DESC_BASE    0x14  /* RW: byte address of the descriptor list, 128 byte aligned */
#define SNPU_REG_DESC_COUNT   0x18  /* RW: number of descriptors to execute */
#define SNPU_REG_IRQ_STATUS   0x1C  /* W1C: bit0 done, bit1 descriptor done, bit2 error, bit3 timeout */
#define SNPU_REG_IRQ_MASK     0x20  /* RW: 1 enables the corresponding IRQ_STATUS bit */
#define SNPU_REG_CYCLE_CNT    0x24  /* RO: cycles spent busy since start */
#define SNPU_REG_STALL_IBUF   0x28  /* RO: cycles spent in the input fill phases (array idle, DDR bound) */
#define SNPU_REG_STALL_WGT    0x2C  /* RO: run phase cycles with no pixel vector entering the array */
#define SNPU_REG_STALL_ACC    0x30  /* RO: cycles with a pixel vector entering the array (MAC cycles) */
#define SNPU_REG_STALL_WR     0x34  /* RO: cycles an output word was held by the write path */
#define SNPU_REG_DESC_DONE    0x38  /* RO: descriptors completed since start */
#define SNPU_REG_TAG          0x3C  /* RO: tag word of the current descriptor */
#define SNPU_REG_DBG0         0x40  /* RO: debug: rd_dma bookkeeping[31:8], seq state[7:3], unit busy, maxpool busy, wr idle */
#define SNPU_REG_DBG1         0x44  /* RO: debug: wr pending[7:0], loaders idle, cmd/data handshakes, AXI valid and ready flags */
#define SNPU_REG_DBG2         0x48  /* RO: debug: write AW wait cycles since reset */
#define SNPU_REG_DBG3         0x4C  /* RO: debug: write W wait cycles after AW accept since reset */
#define SNPU_REG_DBG4         0x50  /* RO: debug: write bursts finished since reset */
#define SNPU_REG_DBG5         0x54  /* RO: debug: write beats sent since reset */

/* Descriptor field accessors: word index, lsb and mask. */
#define SNPU_DF_OPCODE_WORD 0
#define SNPU_DF_OPCODE_LSB  0
#define SNPU_DF_OPCODE_MASK 0xFFu
#define SNPU_DF_FLAGS_WORD 0
#define SNPU_DF_FLAGS_LSB  8
#define SNPU_DF_FLAGS_MASK 0xFFFFu
#define SNPU_DF_VERSION_WORD 0
#define SNPU_DF_VERSION_LSB  24
#define SNPU_DF_VERSION_MASK 0xFFu
#define SNPU_DF_IN_H_WORD 1
#define SNPU_DF_IN_H_LSB  0
#define SNPU_DF_IN_H_MASK 0xFFFFu
#define SNPU_DF_IN_W_WORD 1
#define SNPU_DF_IN_W_LSB  16
#define SNPU_DF_IN_W_MASK 0xFFFFu
#define SNPU_DF_OUT_H_WORD 2
#define SNPU_DF_OUT_H_LSB  0
#define SNPU_DF_OUT_H_MASK 0xFFFFu
#define SNPU_DF_OUT_W_WORD 2
#define SNPU_DF_OUT_W_LSB  16
#define SNPU_DF_OUT_W_MASK 0xFFFFu
#define SNPU_DF_IC_WORD 3
#define SNPU_DF_IC_LSB  0
#define SNPU_DF_IC_MASK 0xFFFFu
#define SNPU_DF_OC_WORD 3
#define SNPU_DF_OC_LSB  16
#define SNPU_DF_OC_MASK 0xFFFFu
#define SNPU_DF_SRC0_BASE_WORD 4
#define SNPU_DF_SRC0_BASE_LSB  0
#define SNPU_DF_SRC0_BASE_MASK 0xFFFFFFFFu
#define SNPU_DF_SRC0_PLANE_STRIDE_WORD 5
#define SNPU_DF_SRC0_PLANE_STRIDE_LSB  0
#define SNPU_DF_SRC0_PLANE_STRIDE_MASK 0xFFFFFFFFu
#define SNPU_DF_SRC0_ROW_STRIDE_WORD 6
#define SNPU_DF_SRC0_ROW_STRIDE_LSB  0
#define SNPU_DF_SRC0_ROW_STRIDE_MASK 0xFFFFFFFFu
#define SNPU_DF_SRC0_PLANES_WORD 7
#define SNPU_DF_SRC0_PLANES_LSB  0
#define SNPU_DF_SRC0_PLANES_MASK 0xFFFFu
#define SNPU_DF_SRC1_PLANES_WORD 7
#define SNPU_DF_SRC1_PLANES_LSB  16
#define SNPU_DF_SRC1_PLANES_MASK 0xFFFFu
#define SNPU_DF_SRC1_BASE_WORD 8
#define SNPU_DF_SRC1_BASE_LSB  0
#define SNPU_DF_SRC1_BASE_MASK 0xFFFFFFFFu
#define SNPU_DF_SRC1_PLANE_STRIDE_WORD 9
#define SNPU_DF_SRC1_PLANE_STRIDE_LSB  0
#define SNPU_DF_SRC1_PLANE_STRIDE_MASK 0xFFFFFFFFu
#define SNPU_DF_SRC1_ROW_STRIDE_WORD 10
#define SNPU_DF_SRC1_ROW_STRIDE_LSB  0
#define SNPU_DF_SRC1_ROW_STRIDE_MASK 0xFFFFFFFFu
#define SNPU_DF_W_BASE_WORD 11
#define SNPU_DF_W_BASE_LSB  0
#define SNPU_DF_W_BASE_MASK 0xFFFFFFFFu
#define SNPU_DF_W_BYTES_PER_OCT_WORD 12
#define SNPU_DF_W_BYTES_PER_OCT_LSB  0
#define SNPU_DF_W_BYTES_PER_OCT_MASK 0xFFFFFFFFu
#define SNPU_DF_PARAM_BASE_WORD 13
#define SNPU_DF_PARAM_BASE_LSB  0
#define SNPU_DF_PARAM_BASE_MASK 0xFFFFFFFFu
#define SNPU_DF_LUT_BASE_WORD 14
#define SNPU_DF_LUT_BASE_LSB  0
#define SNPU_DF_LUT_BASE_MASK 0xFFFFFFFFu
#define SNPU_DF_OUT_BASE_WORD 15
#define SNPU_DF_OUT_BASE_LSB  0
#define SNPU_DF_OUT_BASE_MASK 0xFFFFFFFFu
#define SNPU_DF_OUT_PLANE_STRIDE_WORD 16
#define SNPU_DF_OUT_PLANE_STRIDE_LSB  0
#define SNPU_DF_OUT_PLANE_STRIDE_MASK 0xFFFFFFFFu
#define SNPU_DF_OUT_ROW_STRIDE_WORD 17
#define SNPU_DF_OUT_ROW_STRIDE_LSB  0
#define SNPU_DF_OUT_ROW_STRIDE_MASK 0xFFFFFFFFu
#define SNPU_DF_RES_BASE_WORD 18
#define SNPU_DF_RES_BASE_LSB  0
#define SNPU_DF_RES_BASE_MASK 0xFFFFFFFFu
#define SNPU_DF_RES_PLANE_STRIDE_WORD 19
#define SNPU_DF_RES_PLANE_STRIDE_LSB  0
#define SNPU_DF_RES_PLANE_STRIDE_MASK 0xFFFFFFFFu
#define SNPU_DF_RES_ROW_STRIDE_WORD 20
#define SNPU_DF_RES_ROW_STRIDE_LSB  0
#define SNPU_DF_RES_ROW_STRIDE_MASK 0xFFFFFFFFu
#define SNPU_DF_ZP_IN_WORD 21
#define SNPU_DF_ZP_IN_LSB  0
#define SNPU_DF_ZP_IN_MASK 0xFFu
#define SNPU_DF_ZP_OUT_WORD 21
#define SNPU_DF_ZP_OUT_LSB  8
#define SNPU_DF_ZP_OUT_MASK 0xFFu
#define SNPU_DF_ZP_RES_WORD 21
#define SNPU_DF_ZP_RES_LSB  16
#define SNPU_DF_ZP_RES_MASK 0xFFu
#define SNPU_DF_ZP_OUT2_WORD 21
#define SNPU_DF_ZP_OUT2_LSB  24
#define SNPU_DF_ZP_OUT2_MASK 0xFFu
#define SNPU_DF_RES_MULT_A_WORD 22
#define SNPU_DF_RES_MULT_A_LSB  0
#define SNPU_DF_RES_MULT_A_MASK 0xFFFFu
#define SNPU_DF_RES_SHIFT_A_WORD 22
#define SNPU_DF_RES_SHIFT_A_LSB  16
#define SNPU_DF_RES_SHIFT_A_MASK 0xFFu
#define SNPU_DF_RES_MULT_B_WORD 23
#define SNPU_DF_RES_MULT_B_LSB  0
#define SNPU_DF_RES_MULT_B_MASK 0xFFFFu
#define SNPU_DF_RES_SHIFT_B_WORD 23
#define SNPU_DF_RES_SHIFT_B_LSB  16
#define SNPU_DF_RES_SHIFT_B_MASK 0xFFu
#define SNPU_DF_TILE_ROWS_WORD 24
#define SNPU_DF_TILE_ROWS_LSB  0
#define SNPU_DF_TILE_ROWS_MASK 0xFFFFu
#define SNPU_DF_TILE_PX_WORD 24
#define SNPU_DF_TILE_PX_LSB  16
#define SNPU_DF_TILE_PX_MASK 0xFFFFu
#define SNPU_DF_N_TILES_WORD 25
#define SNPU_DF_N_TILES_LSB  0
#define SNPU_DF_N_TILES_MASK 0xFFFFu
#define SNPU_DF_RING_ROWS_WORD 25
#define SNPU_DF_RING_ROWS_LSB  16
#define SNPU_DF_RING_ROWS_MASK 0xFFFFu
#define SNPU_DF_PAD_T_WORD 26
#define SNPU_DF_PAD_T_LSB  0
#define SNPU_DF_PAD_T_MASK 0xFFu
#define SNPU_DF_PAD_L_WORD 26
#define SNPU_DF_PAD_L_LSB  8
#define SNPU_DF_PAD_L_MASK 0xFFu
#define SNPU_DF_PAD_B_WORD 26
#define SNPU_DF_PAD_B_LSB  16
#define SNPU_DF_PAD_B_MASK 0xFFu
#define SNPU_DF_PAD_R_WORD 26
#define SNPU_DF_PAD_R_LSB  24
#define SNPU_DF_PAD_R_MASK 0xFFu
#define SNPU_DF_K_WORD 27
#define SNPU_DF_K_LSB  0
#define SNPU_DF_K_MASK 0xFu
#define SNPU_DF_STRIDE_WORD 27
#define SNPU_DF_STRIDE_LSB  4
#define SNPU_DF_STRIDE_MASK 0xFu
#define SNPU_DF_TAG_WORD 30
#define SNPU_DF_TAG_LSB  0
#define SNPU_DF_TAG_MASK 0xFFFFFFFFu
#define SNPU_DF_CRC32_WORD 31
#define SNPU_DF_CRC32_LSB  0
#define SNPU_DF_CRC32_MASK 0xFFFFFFFFu

static inline uint32_t snpu_desc_get(const uint32_t *d, int word, int lsb, uint32_t mask)
{
    return (d[word] >> lsb) & mask;
}

static inline void snpu_desc_set(uint32_t *d, int word, int lsb, uint32_t mask, uint32_t v)
{
    d[word] = (d[word] & ~(mask << lsb)) | ((v & mask) << lsb);
}

struct snpu_desc {
    uint32_t w[32];
};

struct snpu_blob_hdr {
    uint32_t magic;          /* BLOB_MAGIC */
    uint32_t version;        /* ISA_VERSION */
    uint32_t base;           /* load address the blob was linked for */
    uint32_t size;           /* total blob size in bytes */
    uint32_t desc_off;       /* offset of the descriptor table */
    uint32_t desc_count;     /* number of descriptors */
    uint32_t param_off;      /* offset of weights, parameters and tables */
    uint32_t param_size;     /* size of that region */
    uint32_t scratch_base;   /* byte address of the activation scratch region */
    uint32_t scratch_size;   /* size of the scratch region */
    uint32_t input_off;      /* offset of the input tensor buffer inside scratch */
    uint32_t input_bytes;    /* input tensor size in bytes */
    uint32_t n_outputs;      /* number of output tensors */
    uint32_t outputs_off;    /* offset of the output table (see OutputEntry) */
    uint32_t crc32;          /* CRC32 of the blob excluding this word */
};

struct snpu_output_entry {
    uint32_t offset;         /* byte offset inside scratch */
    uint32_t h;              /* height */
    uint32_t w;              /* width */
    uint32_t c;              /* real channels */
    uint32_t scale_q16;      /* dequantization scale, unsigned 16.16 fixed point */
    uint32_t zp;             /* zero point, int8 sign extended */
    uint32_t name_off;       /* offset of the zero terminated tensor name */
    uint32_t reserved;       /* 0 */
};

_Static_assert(sizeof(struct snpu_desc) == SNPU_DESC_BYTES, "descriptor size");

#endif /* STALYANPU_ISA_H */
